[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/sections/*"
  to = "/sections/[city].html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
