[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Force trailing slash
[[redirects]]
  from = "/sections/*"
  to = "/sections/:splat/"
  status = 301
  force = true

# Handle 404s
[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404
